<svelte:options immutable={true} />

<script lang="ts">
	import {
		Prop,
		Default,
		Name,
		Signature,
		Description,
	} from "src/components/components-api/props";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
	import { Closed } from "src/components/components-api/events/common/progress";
</script>

<Closed />
<Prop>
	<Name readwrite>reversed</Name>
	<Signature keyword="boolean">
		<Default value={false} />
	</Signature>
	<Description>
		When <code>true</code> the progress direction is reversed.
	</Description>
</Prop>
<BaseComponentProps autoGeneratedId>
	<slot>
		<Dom instances={["HTMLDivElement"]} />
	</slot>
</BaseComponentProps>
