<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Default,
		Name,
		Signature,
		Description,
	} from "src/components/components-api/props";
	import { Ripple, Variant } from "src/components/components-api/props/common";
	import { CommonInputProps } from "src/components/components-api/props/common/input";
</script>

<Props>
	<Ripple />
	<Variant name="InputFieldVariant" allowedValues={["filled", "outlined"]} />
	<Prop>
		<Name>customValidation</Name>
		<Signature keyword="type" name="GetHTMLValidationMsg" />
		<Description
			>A function that has to return a custom error message when the input is
			invalid.</Description
		>
	</Prop>
	<Prop>
		<Name readonly>invalid</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>When the input is invalid it's <code>true</code>.</Description>
	</Prop>
	<Prop>
		<Name>lineRipple</Name>
		<Signature keyword="boolean">
			<Default value={true} />
		</Signature>
		<Description>
			When <code>true</code>, the line ripple is showed.
		</Description>
	</Prop>
	<Prop>
		<Name>type</Name>
		<Signature keyword="type" name="InputFieldType">
			<Default value={"text"} />
		</Signature>
		<Description>
			When the input is invalid it's <code>true</code>.
		</Description>
	</Prop>
	<CommonInputProps autoGeneratedId native instances={["HTMLDivElement"]}>
		<div slot="valueSignature">
			<Signature keyword="type" name="Value" />
		</div>
	</CommonInputProps>
</Props>
