<script lang="ts">
	import { Props } from "src/components/components-api/props";
	import { IconButtonToggleProps } from "src/components/components-api/props/common/button";
</script>

<Props>
	<IconButtonToggleProps autoGeneratedId />
</Props>
