<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Name,
		Default,
		Description,
		Signature,
	} from "src/components/components-api/props";
	import {
		BaseComponentProps,
		Dom,
		Ripple,
		Disabled,
	} from "src/components/components-api/props/common";
	import {
		Selected,
		Value,
	} from "src/components/components-api/props/common/groups";
</script>

<Props target="main">
	<Ripple />
	<Selected />
	<Prop>
		<Name>activated</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>
			When <code>true</code> the component appears activated.
		</Description>
	</Prop>
	<Disabled />
	<Value groupComponent="List" />
	<BaseComponentProps autoGeneratedId stylesTarget="main">
		<Dom instances={["HTMLLIElement"]} />
	</BaseComponentProps>
</Props>
