<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Default,
		Name,
		Signature,
		Description,
	} from "src/components/components-api/props";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
</script>

<Props>
	<Prop>
		<Name>variant</Name>
		<Signature
			keyword="type"
			name="DrawerVariant"
			instances={["permanent", "dismissible", "modal"]}
		>
			<Default value="permanent" />
		</Signature>
		<Description>The variant to use.</Description>
	</Prop>
	<Prop>
		<Name>open</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>
			When <code>true</code> the drawer is open.
		</Description>
	</Prop>
	<Prop>
		<Name>belowTopAppBarProp</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>
			The drawer will try to figure it out when it's positioned below the
			<code>{`<TopAppBar />`}</code>. Whenever this is not possible you can
			force this to
			<code>true</code>.
		</Description>
	</Prop>
	<BaseComponentProps autoGeneratedId>
		<Dom instances={["HTMLDivElement"]} />
	</BaseComponentProps>
</Props>
