<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Default,
		Name,
		Signature,
		Description,
	} from "src/components/components-api/props";
	import {
		BaseComponentProps,
		Dom,
		Variant,
	} from "src/components/components-api/props/common";

</script>

<Props>
	<Variant
		name="DrawerVariant"
		allowedValues={["permanent", "dismissible", "modal"]}
		defaultValue="permanent"
	/>
	<Prop>
		<Name>open</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>
			When <code>true</code> the drawer is open.
		</Description>
	</Prop>
	<BaseComponentProps autoGeneratedId>
		<Dom instances={["HTMLDivElement"]} />
	</BaseComponentProps>
</Props>
