<script lang="ts">
	import { Disabled } from "src/components/components-api/props/common";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
</script>

<Disabled />
<BaseComponentProps autoGeneratedId>
	<Dom instances={["HTMLDivElement"]} />
</BaseComponentProps>
