<svelte:options immutable={true} />

<script lang="ts">
	import { Props, Signature } from "src/components/components-api/props";
	import { CommonMenuSurfaceProps } from "src/components/components-api/props/common/menu";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
	import { CommonListProps } from "src/components/components-api/props/common/list";
	import { CommonGroupsProps } from "src/components/components-api/props/common/groups";
</script>

<Props>
	<CommonMenuSurfaceProps tag="Menu" />
	<CommonListProps tag="Menu" />
	<CommonGroupsProps>
		<svelte-fragment slot="valueSignature">
			<Signature keyword="string" />
		</svelte-fragment>
	</CommonGroupsProps>
	<BaseComponentProps autoGeneratedId>
		<Dom instances={["HTMLDivElement"]} />
	</BaseComponentProps>
</Props>
