<svelte:options immutable={true} />

<script lang="ts">
	import { Props, Signature } from "src/components/components-api/props";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
	import { CommonGroupsProps } from "src/components/components-api/props/common/groups";
</script>

<Props>
	<CommonGroupsProps multi showGroup showNullable groupComponent="DataTable">
		<svelte-fragment slot="valueSignature">
			<Signature keyword="type" name="ChipSetValue" />
		</svelte-fragment>
	</CommonGroupsProps>
	<BaseComponentProps autoGeneratedId stylesTarget="main">
		<Dom instances={["HTMLDivElement"]} />
	</BaseComponentProps>
</Props>
