<svelte:options immutable={true} />

<script lang="ts">
	import { Class, StyleProp, Id } from ".";

	export let autoGeneratedId: boolean = false;
	export let stylesTarget: "root" | "main" = "root";
</script>

<slot />
<Class target={stylesTarget} />
<StyleProp target={stylesTarget} />
<Id autoGenerated={autoGeneratedId} />
