<script lang="ts">
	import { Prop, Name, Description, Signature } from "..";

	export let autoGenerated: boolean = false;
</script>

<Prop>
	<Name>id</Name>
	{#if autoGenerated}
		<Signature keyword="string">Auto generated</Signature>
	{:else}
		<Signature keyword="string" />
	{/if}
	<Description>
		A string that overwrite the value of the
		<code>id</code>
		attribute of the root
		<code>HTMLElement</code>. It can be used to assign custom id to the
		component's root element.
	</Description>
</Prop>
