<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Default,
		Name,
		Signature,
		Description,
	} from "src/components/components-api/props";
	import { Ripple } from "src/components/components-api/props/common";
	import { CommonInputProps } from "src/components/components-api/props/common/input";

	export let nativeInputElement: string = "input";
</script>

<Props>
	<Ripple />
	<Prop>
		<Name>customValidation</Name>
		<Signature keyword="type" name="GetHTMLValidationMsg" />
		<Description
			>A function that has to return a custom error message when the input is
			invalid.</Description
		>
	</Prop>
	<Prop>
		<Name readwrite>invalid</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>When the input is invalid it's <code>true</code>.</Description>
	</Prop>
	<slot />
	<CommonInputProps
		autoGeneratedId
		native={nativeInputElement}
		instances={["HTMLDivElement"]}
	>
		<div slot="valueSignature">
			<Signature keyword="type" name="Value" />
		</div>
	</CommonInputProps>
</Props>
