<svelte:options immutable={true} />

<script lang="ts">
	import { Signature } from "src/components/components-api/events";

	import { Disabled } from "src/components/components-api/props/common";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
	import { Value } from "src/components/components-api/props/common";

	export let stylesTarget: "root" | "main" = "root";
	export let groupComponent: string = undefined;
	export let native: boolean = false;
	export let instances: string[] = ["HTMLDivElement"];
	export let autoGeneratedId: boolean = false;
</script>

<Disabled />
{#if $$slots.valueSignature}
	<Value {groupComponent} {native}>
		<slot slot="signature" name="valueSignature">
			<Signature keyword="string" />
		</slot>
	</Value>
{/if}
<BaseComponentProps {autoGeneratedId} {stylesTarget}>
	<slot>
		<Dom {instances} />
	</slot>
</BaseComponentProps>
