<svelte:options immutable={true} />

<script lang="ts">
	import { Disabled } from "src/components/components-api/props/common";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
	import { Value } from "src/components/components-api/props/common/groups";

	export let stylesTarget: "root" | "main" = "root";
	export let groupComponent: string = undefined;
	export let native: boolean = false;
	export let instances: string[] = ["HTMLDivElement"];
	export let autoGeneratedId: boolean = false;
</script>

<Disabled />
<Value {groupComponent} {native} />
<BaseComponentProps {autoGeneratedId} {stylesTarget}>
	<slot>
		<Dom {instances} />
	</slot>
</BaseComponentProps>
