<svelte:options immutable={true} />

<script lang="ts">
	import {
		Disabled,
		ReadOnly,
	} from "src/components/components-api/props/common";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
</script>

<Disabled />
<ReadOnly />
<BaseComponentProps autoGeneratedId>
	<slot>
		<Dom instances={["HTMLDivElement"]} />
	</slot>
</BaseComponentProps>
