<svelte:options immutable={true} />

<script lang="ts">
	import { Signature } from "src/components/components-api/props";
	import { CommonInputProps } from "src/components/components-api/props/common/input";

	export let nativeInputElement: string = "input";
</script>

<CommonInputProps
	autoGeneratedId
	native={nativeInputElement}
	instances={["HTMLDivElement"]}
>
	<slot name="valueSignature" slot="valueSignature">
		<Signature keyword="type" name="Value" />
	</slot>
</CommonInputProps>
