<script lang="ts">
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
</script>

<BaseComponentProps autoGeneratedId>
	{#if $$slots.default}
		<slot />
	{:else}
		<Dom
			keyword="type"
			name="ButtonDOM"
			instances={['HTMLButtonElement', 'HTMLAnchorElement']}>
			It's
			<code>HTMLAnchorElement</code>
			when
			<code>href</code>
			is not empty; otherwise it's
			<code>HTMLButtonElement</code>.
		</Dom>
	{/if}
</BaseComponentProps>
