<script lang="ts">
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";

	export let autoGeneratedId: boolean = false;
</script>

<BaseComponentProps {autoGeneratedId}>
	<slot>
		<Dom
			keyword="type"
			name="ButtonDOM"
			instances={['HTMLButtonElement', 'HTMLAnchorElement']}>
			It's
			<code>HTMLAnchorElement</code>
			when
			<code>href</code>
			is not empty; otherwise it's
			<code>HTMLButtonElement</code>.
		</Dom>
	</slot>
</BaseComponentProps>
