<svelte:options immutable={true} />

<script lang="ts">
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
</script>

<BaseComponentProps autoGeneratedId>
	<Dom instances={["HTMLUListElement"]} />
</BaseComponentProps>
