<svelte:options immutable={true} />

<script lang="ts">
	import { Props } from "src/components/components-api/props";
	import { Ripple, Value } from "src/components/components-api/props/common";
	import { Selected } from "src/components/components-api/props/common/groups";
	import { CommonInputProps } from "src/components/components-api/props/common/input";
</script>

<Props target="main">
	<Value />
	<Ripple />
	<Selected />
	<slot />
	<CommonInputProps
		autoGeneratedId
		stylesTarget="main"
		groupComponent="List"
		instances={["HTMLLIElement"]}
	/>
</Props>
