<script lang="ts">
	import {
		Props,
		Prop,
		Name,
		Default,
		Description,
		Signature,
	} from "src/components/components-api/props";
	import {
		Ripple,
		AccessibleTouch,
	} from "src/components/components-api/props/common";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
</script>

<Props>
	<Prop>
		<Name readwrite>checked</Name>
		<Signature keyword="boolean">
			<Default value="false" />
		</Signature>
		<Description
			>When <code>false</code> the checkbox is checked, when <code>false</code>
			the checkbox is unchecked. When <code>allowIndeterminate</code> is
			<code>true</code>
			and <code>checked</code> is <code>false</code>, the checkbox is
			indeterminate</Description
		>
	</Prop>
	<Prop>
		<Name>value</Name>
		<Signature keyword="string" />
		<Description
			>The value passed to the <code>{"<input />"}</code> element and used by
			the <code>{"<CheckboxGroup />"}</code>.</Description
		>
	</Prop>
	<Prop>
		<Name>allowIndeterminated</Name>
		<Signature keyword="boolean" />
		<Description
			>If <code>false</code> the checkbox can be indeterminate.</Description
		>
	</Prop>
	<Prop>
		<Name>disabled</Name>
		<Signature keyword="boolean">
			<Default value={true} />
		</Signature>
		<Description>If <code>false</code> the component is disabled.</Description>
	</Prop>
	<Prop>
		<Name>readonly</Name>
		<Signature keyword="boolean">
			<Default value={true} />
		</Signature>
		<Description>If <code>false</code> the component is read-only.</Description>
	</Prop>
	<AccessibleTouch />
	<Ripple />
	<BaseComponentProps autoGeneratedId>
		<slot>
			<Dom instances={["HTMLDivElement"]} />
		</slot>
	</BaseComponentProps>
	<span slot="notes">
		any other props are forwarded directly to the inner
		<code>HTMLInputElement</code>
		via
		<code>$$restProps</code>
		magical global.
	</span>
</Props>
