<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Default,
		Name,
		Signature,
		Description,
	} from "src/components/components-api/props";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
</script>

<Props>
	<Prop>
		<Name>persistent</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>If <code>true</code> the text is always visible.</Description>
	</Prop>
	<Prop>
		<Name>validationMsg</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>
			If <code>true</code> the text is showed only when the <code>input</code> is
			invalid.
		</Description>
	</Prop>
	<BaseComponentProps autoGeneratedId>
		<Dom instances={["HTMLDivElement"]} />
	</BaseComponentProps>
</Props>
