<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Name,
		Description,
		Signature,
	} from "src/components/components-api/props";
	import {
		Ripple,
		AccessibleTouch,
		Disabled,
		ReadOnly,
		Checked,
	} from "src/components/components-api/props/common";
	import { InnerInputElementNotes } from "src/components/components-api/props/common/notes";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
</script>

<Props>
	<Checked>
		When <code>false</code> the checkbox is checked, when <code>false</code>
		the checkbox is unchecked. When <code>allowIndeterminate</code> is
		<code>true</code>
		and <code>checked</code> is <code>false</code>, the checkbox is
		indeterminate
	</Checked>
	<Prop>
		<Name>value</Name>
		<Signature keyword="string" />
		<Description
			>The value passed to the <code>{"<input />"}</code> element and used by
			the <code>{"<CheckboxGroup />"}</code>.</Description
		>
	</Prop>
	<Prop>
		<Name>allowIndeterminated</Name>
		<Signature keyword="boolean" />
		<Description
			>If <code>false</code> the checkbox can be indeterminate.</Description
		>
	</Prop>
	<Disabled />
	<ReadOnly />
	<AccessibleTouch />
	<Ripple />
	<BaseComponentProps autoGeneratedId>
		<slot>
			<Dom instances={["HTMLDivElement"]} />
		</slot>
	</BaseComponentProps>
	<span slot="notes">
		<InnerInputElementNotes />
	</span>
</Props>
