<svelte:options immutable={true} />

<script lang="ts">
	import { Props, Default } from "src/components/components-api/props";
	import { Dom, Variant } from "src/components/components-api/props/common";
	import {
		Prop,
		Name,
		Description,
		Signature,
	} from "src/components/components-api/props";
	import { BaseButtonProps } from "src/components/components-api/props/common/button";

</script>

<Props>
	<Variant
		name="ImageListVariant"
		allowedValues={["standard", "masonry"]}
		defaultValue="standard"
	/>
	<Prop>
		<Name>textProtection</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>
			Indicates that supporting content should be positioned in a scrim
			overlaying each image (instead of positioned separately under each image).
		</Description>
	</Prop>
	<BaseButtonProps autoGeneratedId>
		<Dom instances={["HTMLUListElement"]} />
	</BaseButtonProps>
</Props>
