<svelte:options immutable={true} />

<script lang="ts">
	import { Props } from "src/components/components-api/props";
	import { ReadOnly } from "src/components/components-api/props/common";
	import {
		Ripple,
		AccessibleTouch,
	} from "src/components/components-api/props/common";
	import {
		Selected,
		Value,
	} from "src/components/components-api/props/common/groups";
	import { InnerInputElementNotes } from "src/components/components-api/props/common/notes";
	import { CommonInputProps } from "src/components/components-api/props/common/input";
</script>

<Props>
	<Selected name="checked" />
	<AccessibleTouch />
	<Ripple />
	<ReadOnly />
	<CommonInputProps
		autoGeneratedId
		stylesTarget="main"
		groupComponent="RadioGroup"
		native
	/>
	<span slot="notes">
		<InnerInputElementNotes />
	</span>
</Props>
