<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Name,
		Description,
		Signature,
	} from "src/components/components-api/props";
	import {
		Ripple,
		AccessibleTouch,
		Disabled,
		ReadOnly,
		Checked,
	} from "src/components/components-api/props/common";
	import { InnerInputElementNotes } from "src/components/components-api/props/common/notes";
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/props/common";
</script>

<Props>
	<Checked />
	<Prop>
		<Name>value</Name>
		<Signature keyword="string" />
		<Description
			>The value passed to the inner <code>{"<input />"}</code> element and used
			by the <code>{"<RadioGroup />"}</code>.</Description
		>
	</Prop>
	<Disabled />
	<ReadOnly />
	<AccessibleTouch />
	<Ripple />
	<BaseComponentProps autoGeneratedId>
		<slot>
			<Dom instances={["HTMLDivElement"]} />
		</slot>
	</BaseComponentProps>
	<span slot="notes">
		<InnerInputElementNotes />
	</span>
</Props>
