<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Name,
		Default,
		Description,
		Signature,
	} from "src/components/components-api/props";
	import {
		BaseComponentProps,
		Dom,
		Open,
	} from "src/components/components-api/props/common";

</script>

<Props>
	<Prop>
		<Name>stackedOnMobile</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>Show actions below text on mobile.</Description>
	</Prop>
	<Prop>
		<Name>fixed</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>
			Force <code>{`<Banner />`}</code> to remain fixed at the top of the
			screen. To be used when <code>{`<Banner />`}</code> is used below
			<code>{`<TopAppBar />`}</code>.
		</Description>
	</Prop>
	<Prop>
		<Name>centered</Name>
		<Signature keyword="boolean">
			<Default value={false} />
		</Signature>
		<Description>
			Sets the <code>{`<Banner />`}</code> content to centered instead of leading.
		</Description>
	</Prop>
	<Open readwrite tag="Banner" />
	<BaseComponentProps autoGeneratedId>
		<Dom instances={["HTMLDivElement"]} />
	</BaseComponentProps>
</Props>
