<svelte:options immutable={true} />

<script lang="ts">
	import { Props } from "src/components/components-api/props";
	import { ReadOnly } from "src/components/components-api/props/common";
	import { Ripple } from "src/components/components-api/props/common";
	import { CommonInputProps } from "src/components/components-api/props/common/input";
	import { Selected } from "src/components/components-api/props/common/groups";

</script>

<Props>
	<Selected name="checked" />
	<Ripple />
	<ReadOnly />
	<CommonInputProps autoGeneratedId groupComponent="SwitchGroup" native />
</Props>
