<script lang="ts">
	import {
		Class,
		StyleProp,
		Id,
	} from "src/components/components-api/common/props";

	export let autoGeneratedId: boolean = false;
</script>

<slot />
<Class />
<StyleProp />
<Id autoGenerated={autoGeneratedId} />
