<svelte:options immutable={true} />

<script lang="ts">
	import {
		Props,
		Prop,
		Name,
		Description,
		Signature,
	} from "src/components/components-api/props";
	import { ReadOnly } from "src/components/components-api/props/common";
	import {
		Ripple,
		AccessibleTouch,
	} from "src/components/components-api/props/common";
	import { CommonInputProps } from "src/components/components-api/props/common/input";
	import { Selected } from "src/components/components-api/props/common/groups";
	import { InnerInputElementNotes } from "src/components/components-api/props/common/notes";
</script>

<Props>
	<Selected name="checked">
		When <code>true</code> the checkbox is checked, when <code>false</code>
		the checkbox is unchecked. When <code>allowIndeterminate</code> is
		<code>true</code>
		and <code>checked</code> is <code>null</code>, the checkbox is indeterminate
	</Selected>
	<Prop>
		<Name>allowIndeterminated</Name>
		<Signature keyword="boolean" />
		<Description
			>When <code>true</code> the checkbox can be indeterminate.</Description
		>
	</Prop>
	<AccessibleTouch />
	<Ripple />
	<ReadOnly />
	<CommonInputProps
		autoGeneratedId
		stylesTarget="main"
		groupComponent="CheckboxGroup"
		native
	/>
	<span slot="notes">
		<InnerInputElementNotes />
	</span>
</Props>
