<script lang="ts">
	import {
		BaseComponentProps,
		Dom,
	} from "src/components/components-api/common/props";
</script>

<BaseComponentProps autoGeneratedId>
	<Dom
		keyword="type"
		name="ButtonDOM"
		instances={['HTMLButtonElement', 'HTMLAnchorElement']}>
		<span slot="additional-dom-desc">
			It's
			<code>HTMLAnchorElement</code>
			when
			<code>href</code>
			is not empty; otherwise it's
			<code>HTMLButtonElement</code>.
		</span>
	</Dom>
</BaseComponentProps>
